### PR TITLE
add codec transcoding dynamically typed Object values

### PR DESCRIPTION
**Pull request by t-beckmann**
Contributing this codec which is based on the code inside of org.bson.codecs.IterableCodec. I'm using it as a last resort in my chain of codecs. It allows fields typed as plain `Object` to be transcoded using their closest BSON counterparts.

### CODE REVIEW

**Comment by webermich** [comment]
I do not quite understand the use case of a codec that is able to decode/encode property fields of type Object.class?
Mostly you have total control over your Pojos and can declare them carefully.
Could you sketch an example where I would need such a codec?

**Comment by t-beckmann** [comment]
Well, in my case the software being developed has both an SQL database and a MongoDB. In some parts of the code I specifically preferred MongoDB as a storage means because it may operate schemaless and store arbitrary values. We are storing data coming from IoT sensors, where some sensors provide integral values, others floating points and some even arbitrary precision values. With the MongoDB I can store all of this in a mixed way and still perform aggregations like like min and max. When aggregating, the resulting values are of reasonable precision as well.

**Comment by webermich** [comment]
I merged you pull request, but (unfortunately) did not make sure it working with JDK 1.8
When compiling with an old JDK 1.8 I am getting the following error:
```
/polymorphia/src/main/java/de/bild/codec/ObjectCodec.java:[60,54] incompatible types: inferred type does not conform to equality constraint(s)
    inferred: capture#1 of ? extends U
    equality constraints(s): capture#1 of ? extends U,T
```

Currently I still want to support 1.8 hence may I kindly ask you to change the code so that it compiles with JDK 1.8?

Thanks a lot.

**Comment by webermich** [comment]
I'd reckon the cause of the compiler error is similar to that issue, although I was using oracle JDK to compile.
https://bugs.openjdk.java.net/browse/JDK-8153180

I think the solution could be something like:
`final Codec encoder = registry.get(value.getClass());`
instead of 
`final Codec<T> encoder = registry.get(value.getClass().asSubclass(clazz));`

With your permission I'd change it and trigger a new release?

**Comment by t-beckmann** [comment]
Yes please, regarding the generic the older compiler is a pain.
